### ISSUE TITLE
Weird printf output

### ISSUE THREAD

**Issue by dezza** [jreese/zsh-titles#4]
Normal printf:

``` zsh
~ $ printf "%s" "john"
john%      
```

With zsh-titles:

``` zsh
~ $ printf "%s" "john"
" "john":~john% 
```

**Comment by amyreese** [comment]
Interesting.  I can only reproduce this inside of tmux, though.  In just a standard terminal window, I get the "normal" result.  If you have an idea how to resolve this, I'd be happy to give it a try, but I'm not familiar enough to know how to debug this on my own.

**Comment by dezza** [comment]
https://github.com/jreese/zsh-titles/blob/master/titles.plugin.zsh#L10-L14
I have a SSH client that sets xterm-256color - so that might be why I see it too.

Could be it is the nested $a variable that does it.

Will perform some tests.

**Comment by dezza** [comment]
Pull request https://github.com/jreese/zsh-titles/pull/5

Should fix it :)

**Comment by dezza** [comment]
https://github.com/jreese/zsh-titles/pull/6

Proper fix this time I hope :)

**Comment by dezza** [comment]
```sh
printf "\e[31mRed"
Red":~Red%
```
The same happens with `echo` and `print`

If you replace `print -n` with `printf` it just works (prints only `Red`)

~~#12~~
( thought I had fixed this )

Trying again.

**Comment by dezza** [comment]
Okay I finally found the culprit.

Escape sequences are evaluated when they are defined.

So that causes problems because that displays characters which are not supposed to show
```sh
~ \e
~zsh: command not found: e
```
^ that `~` is not supposed to be there. Any "\\" can essentially break the plugin.

The only solution I can think of and found by searching is that you escape "\\".

PR:
#13
